# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no_shares', models.IntegerField()),
                ('profit', models.FloatField()),
                ('invested', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('PE', models.DecimalField(decimal_places=3, max_digits=6)),
                ('change_pct', models.DecimalField(decimal_places=5, max_digits=5)),
                ('last', models.DecimalField(decimal_places=3, max_digits=6)),
                ('short_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('buying_date', models.DateTimeField(default=datetime.datetime(2017, 11, 14, 7, 17, 27, 685271))),
                ('current_date', models.DateField(auto_now=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sum_invested', models.FloatField()),
                ('sum_profit', models.FloatField()),
                ('my_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Basket')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='my_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Stock'),
        ),
    ]
