# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171006_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(default='___', max_length=20),
            preserve_default=False,
        ),
    ]
