# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_basket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='PE',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 13, 24, 34, 573620)),
        ),
        migrations.AddField(
            model_name='stock',
            name='change_pct',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='short_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
