# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20171114_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 7, 23, 25, 801319)),
        ),
    ]
