# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20171024_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 18, 25, 36, 438536)),
        ),
    ]
