# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20171109_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 19, 44, 52, 852713)),
        ),
    ]
