# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20171109_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 4, 59, 29, 351673)),
        ),
    ]
