# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_auto_20171114_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='diff',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buying_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 12, 41, 50, 284014)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 12, 41, 50, 284014)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='past_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 12, 41, 50, 284014)),
        ),
    ]
